platform :ios, '8.0'
use_frameworks!

target 'SimpleCIDummyProject' do
pod 'ReactiveCocoa', '4.0.4-alpha-1'
pod 'AFNetworking', '3.0.0-beta.2'
pod 'HexColors', '~> 3.0'
pod 'CocoaLumberjack', '~> 2.2'
pod 'MDMCoreData', '~> 1.5'
pod 'Watchdog', '~> 1.0'
pod 'Groot/ObjC'
pod 'SSKeychain', '~> 1.3'
pod 'FBSDKCoreKit', '4.9.0-beta2'
pod 'FBSDKLoginKit', '4.9.0-beta2'
pod 'FBSDKShareKit', '4.9.0-beta2'
pod 'SWRevealViewController', '~> 2.3'
pod 'SVPullToRefresh'
pod 'youtube-ios-player-helper', '0.1.4'
pod 'Fabric'
pod 'Crashlytics'
pod 'RSKImageCropper', '~> 1.5'
pod 'SwiftyJSON', '2.3.0'
pod 'Charts', '2.1.4'
pod 'UIColor_Hex_Swift', '~> 1.2' # Library for insert colours in Hexadecimal
pod 'RealmSwift', '0.96.2'
pod 'MGSwipeTableCell', '1.5.1'
pod 'Alamofire', '3.1.4'
pod 'PKHUD', '2.2.5'
pod 'AlamofireImage', '2.2.0'
end

